[app]
port = 8080
mode = 'dev'
[app.log]
    format = '%(asctime)s - %(name)s - %(levelname)s - %(lineno)d - %(module)s - %(message)s'

[database]
pool = 5
user = 'root'
password = '613fb94fbd740f66'
host = 'wghtstudio.cn'
port = 3306
db = 'home_designer'